// Bethesda CD - every word the window says, in one place: French first (the staff's
// language); Korean and English are for the people who install and support it.
// The language is the line "lang=" of Bethesda-CD.ini (fr when there is none).
using System.Collections.Generic;

namespace Bethesda.Cd {
  public static class Texts {
    public static string Lang = "fr";
    public static string Unit { get { return Lang == "fr" ? "Mo" : "MB"; } }
    static int Column { get { return Lang == "ko" ? 1 : Lang == "en" ? 2 : 0; } }
    public static bool Known(string lang) { return lang == "fr" || lang == "ko" || lang == "en"; }

    public static string Get(string key) { string[] v; return T.TryGetValue(key, out v) ? v[Column] : key; }
    public static string Get(string key, params object[] a) { return string.Format(Get(key), a); }
    public static bool Has(string key) { return T.ContainsKey(key); }
    // The words for a refusal: by its code, and the reason as it came when the code is unknown.
    public static string Error(string code, string detail, params object[] a) {
      if (!T.ContainsKey("e_" + code)) return Get("e_other", (code + " " + detail).Trim());
      return string.Format(Get("e_" + code), a.Length == 0 ? new object[] { "", "" } : a);
    }

    static readonly Dictionary<string, string[]> T = new Dictionary<string, string[]> {
      //                  French                                         Korean                                   English
      { "title",      new[] { "Bethesda CD — Copie et importation d'images", "Bethesda CD — 영상 내보내기 · 들여오기", "Bethesda CD — Copy out and bring in images" } },
      { "emrUrl",     new[] { "Adresse de l'EMR", "EMR 주소", "EMR address" } },
      { "login",      new[] { "Identifiant", "아이디", "Login" } },
      { "password",   new[] { "Mot de passe", "비밀번호", "Password" } },
      { "signIn",     new[] { "Se connecter", "로그인", "Sign in" } },
      { "signOut",    new[] { "Se déconnecter", "로그아웃", "Sign out" } },
      { "loginHint",  new[] { "Connectez-vous avec votre compte de l'EMR.", "EMR 계정으로 로그인하세요.", "Sign in with your EMR account." } },
      { "connected",  new[] { "Connecté : {0}", "로그인: {0}", "Signed in: {0}" } },
      { "chart",      new[] { "N° dossier", "차트번호", "Chart no." } },
      { "search",     new[] { "Chercher", "조회", "Find" } },
      { "patient",    new[] { "{0} — né(e) le {1} — {2}", "{0} — 생년월일 {1} — {2}", "{0} — born {1} — {2}" } },
      { "noPatientYet", new[] { "Tapez le N° dossier du patient, puis Entrée.", "환자의 차트번호를 치고 Enter를 누르세요.", "Type the patient's chart number, then Enter." } },
      { "colDate",    new[] { "Date", "날짜", "Date" } },
      { "colType",    new[] { "Type", "종류", "Type" } },
      { "colExam",    new[] { "Examen", "검사", "Exam" } },
      { "colImages",  new[] { "Images", "영상", "Images" } },
      { "colSize",    new[] { "Taille", "크기", "Size" } },
      { "colState",   new[] { "État", "상태", "State" } },
      { "selNone",    new[] { "Cochez les examens à copier.", "반출할 검사를 체크하세요.", "Tick the exams to copy." } },
      { "sel",        new[] { "Sélection : {0} examen(s) · {1} image(s) · {2}", "선택: 검사 {0}건 · 영상 {1}장 · {2}", "Chosen: {0} exam(s) · {1} image(s) · {2}" } },
      { "selMax",     new[] { "Au plus {0} examens à la fois.", "한 번에 {0}건까지입니다.", "At most {0} exams at a time." } },
      { "noBurner",   new[] { "Aucun graveur sur ce PC — « Enregistrer en fichier ISO » et « Enregistrer dans un dossier » restent possibles.", "이 PC에는 굽는 드라이브가 없습니다 — 「ISO 파일로 저장」과 「폴더에 저장」은 됩니다.", "No disc burner on this PC — \"Save as ISO file\" and \"Save to a folder\" still work." } },
      { "noDisc",     new[] { "Graveur {0} — insérez un disque vierge.", "드라이브 {0} — 빈 디스크를 넣으세요.", "Burner {0} — insert a blank disc." } },
      { "discBlank",  new[] { "Graveur {0} — {1} vierge, {2} libres", "드라이브 {0} — 빈 {1}, {2} 남음", "Burner {0} — blank {1}, {2} free" } },
      { "fits",       new[] { "  ✔ tient sur ce disque", "  ✔ 이 디스크에 들어갑니다", "  ✔ fits on this disc" } },
      { "tooBig",     new[] { "  ✘ {0} de trop : décochez un examen ou utilisez un DVD", "  ✘ {0} 넘침: 검사를 줄이거나 DVD를 쓰세요", "  ✘ {0} too much: untick an exam or use a DVD" } },
      { "discUsed",   new[] { "Graveur {0} — ce disque n'est pas vierge : il ne sera pas utilisé.", "드라이브 {0} — 빈 디스크가 아닙니다. 이 디스크에는 굽지 않습니다.", "Burner {0} — this disc is not blank: it will not be used." } },
      { "stViewer",   new[] { "Ajout de la visionneuse…", "뷰어를 넣는 중…", "Adding the viewer…" } },
      { "noViewer",   new[] { "\n\n(La visionneuse VIEWER.EXE n'a pas pu être ajoutée : {0})", "\n\n(뷰어 VIEWER.EXE를 넣지 못했습니다: {0})", "\n\n(The viewer VIEWER.EXE could not be added: {0})" } },
      { "unpacked",   new[] { "\n\n(Certaines images étaient dans un format que la visionneuse ne lit pas : toutes les images de cette copie ont été décompressées, sans perte. La copie est plus volumineuse.)",
                              "\n\n(뷰어가 읽지 못하는 형식의 영상이 있어, 이 사본의 영상을 모두 압축을 풀어 넣었습니다(화질 손실 없음). 사본이 더 큽니다.)",
                              "\n\n(Some images were in a format the viewer does not read: every image of this copy was decompressed, without loss. The copy is larger.)" } },
      { "burn",       new[] { "Graver ce CD…", "이 CD에 굽기…", "Burn this CD…" } },
      { "iso",        new[] { "Enregistrer en fichier ISO…", "ISO 파일로 저장…", "Save as ISO file…" } },
      { "folder",     new[] { "Enregistrer dans un dossier…", "폴더에 저장…", "Save to a folder…" } },
      { "askBurn",    new[] { "Graver {0} examen(s) ({1}) de {2} sur le disque du lecteur {3} ?", "{2} 님의 검사 {0}건({1})을 {3} 드라이브의 디스크에 구울까요?", "Burn {0} exam(s) ({1}) of {2} to the disc in drive {3}?" } },
      { "askFolder",  new[] { "Choisissez le dossier (ou la clé USB) où créer la copie", "사본을 만들 폴더(또는 USB)를 고르세요", "Choose the folder (or USB stick) where the copy is made" } },
      { "stFetch",    new[] { "Récupération des images… {0}", "영상을 받는 중… {0}", "Fetching the images… {0}" } },
      { "stReadme",   new[] { "Préparation du disque…", "디스크 내용을 준비하는 중…", "Preparing the disc…" } },
      { "stCopy",     new[] { "Copie… {0} / {1}", "복사 중… {0} / {1}", "Copying… {0} / {1}" } },
      { "stImage",    new[] { "Préparation de l'image du disque…", "디스크 이미지를 만드는 중…", "Preparing the disc image…" } },
      { "stIso",      new[] { "Écriture du fichier ISO… {0} %", "ISO 파일을 쓰는 중… {0} %", "Writing the ISO file… {0} %" } },
      { "stBurn",     new[] { "Gravure en cours… {0} %   {1}", "굽는 중… {0} %   {1}", "Burning… {0} %   {1}" } },
      { "stCheck",    new[] { "Vérification du disque…", "구운 디스크를 확인하는 중…", "Checking the disc…" } },
      { "doneFolder", new[] { "Terminé. La copie est dans :\n{0}\n\n{1} fichiers, {2}. Chaque fichier a été relu et comparé.\n\nCe dossier contient les images d'un patient : supprimez-le quand il n'est plus utile.",
                              "끝났습니다. 사본의 자리:\n{0}\n\n파일 {1}개, {2}. 파일마다 다시 읽어 원본과 비교했습니다.\n\n이 폴더에는 환자의 영상이 들어 있습니다. 쓸 일이 끝나면 지우세요.",
                              "Done. The copy is in:\n{0}\n\n{1} files, {2}. Every file was read back and compared.\n\nThis folder holds a patient's images: delete it when it is no longer needed." } },
      { "doneIso",    new[] { "Terminé. Fichier ISO :\n{0}\n({1})\n\nCe fichier contient les images d'un patient : supprimez-le quand il n'est plus utile.",
                              "끝났습니다. ISO 파일:\n{0}\n({1})\n\n이 파일에는 환자의 영상이 들어 있습니다. 쓸 일이 끝나면 지우세요.",
                              "Done. ISO file:\n{0}\n({1})\n\nThis file holds a patient's images: delete it when it is no longer needed." } },
      { "doneBurn",   new[] { "Terminé : le disque est gravé et vérifié.\n\nÉcrivez le nom du patient et la date sur le disque.", "끝났습니다. 디스크를 굽고 확인했습니다.\n\n디스크에 환자 이름과 날짜를 적으세요.", "Done: the disc is burnt and checked.\n\nWrite the patient's name and the date on the disc." } },
      { "doneBurnDrive", new[] { "Terminé : le disque est gravé (vérifié par le graveur).\n\nÉcrivez le nom du patient et la date sur le disque.", "끝났습니다. 디스크를 구웠습니다(드라이브가 확인함).\n\n디스크에 환자 이름과 날짜를 적으세요.", "Done: the disc is burnt (checked by the burner).\n\nWrite the patient's name and the date on the disc." } },
      { "doneBurnUnread", new[] { "Le disque est gravé, mais il n'a pas pu être relu pour la vérification.\nRemettez-le dans le lecteur et vérifiez qu'il s'ouvre avant de le remettre.", "디스크는 구웠지만, 확인하려고 다시 읽지 못했습니다.\n디스크를 다시 넣어 열리는지 본 뒤에 건네세요.", "The disc is burnt, but it could not be read back for the check.\nPut it back in the drive and see that it opens before handing it over." } },
      { "badBurn",    new[] { "La gravure a échoué : ce disque est à jeter.\n{0}\n\nMettez un autre disque vierge et recommencez.", "굽기에 실패했습니다. 이 디스크는 버리세요.\n{0}\n\n다른 빈 디스크를 넣고 다시 하세요.", "Burning failed: throw this disc away.\n{0}\n\nInsert another blank disc and start again." } },
      { "badVerify",  new[] { "La vérification a échoué — ne remettez pas ce disque.\n{0} fichier(s) différent(s). Mettez un autre disque vierge et recommencez.", "확인에서 어긋났습니다 — 이 디스크를 건네지 마세요.\n다른 파일 {0}개. 다른 빈 디스크를 넣고 다시 하세요.", "The check failed — do not hand this disc over.\n{0} file(s) differ. Insert another blank disc and start again." } },
      { "busyClose",  new[] { "Un travail est en cours. Attendez qu'il se termine (une importation peut être annulée).", "일하는 중입니다. 끝날 때까지 기다리세요(들여오기는 취소할 수 있습니다).", "Work is in progress. Wait until it is finished (bringing in can be cancelled)." } },
      { "expired",    new[] { "La session a expiré. Reconnectez-vous.", "로그인이 만료되었습니다. 다시 로그인하세요.", "The session has expired. Sign in again." } },
      { "male",       new[] { "M", "남", "M" } },
      { "female",     new[] { "F", "여", "F" } },
      { "e_BAD_URL",  new[] { "L'adresse de l'EMR doit commencer par http:// (exemple : http://192.168.1.10:9080).", "EMR 주소는 http:// 로 시작해야 합니다(예: http://192.168.1.10:9080).", "The EMR address must start with http:// (example: http://192.168.1.10:9080)." } },
      { "e_NO_ANSWER", new[] { "L'EMR ne répond pas à cette adresse. Vérifiez l'adresse et le réseau.", "이 주소에서 EMR이 응답하지 않습니다. 주소와 네트워크를 확인하세요.", "The EMR does not answer at this address. Check the address and the network." } },
      { "e_NOT_EMR",  new[] { "Cette adresse répond, mais ce n'est pas l'EMR.", "이 주소는 응답하지만 EMR이 아닙니다.", "This address answers, but it is not the EMR." } },
      { "e_WRONG_LOGIN", new[] { "Identifiant ou mot de passe incorrect.", "아이디 또는 비밀번호가 틀렸습니다.", "Wrong login or password." } },
      { "e_FORBIDDEN", new[] { "Ce compte ne peut ni copier ni importer des images (il faut Consultation, Paiement ou Enregistrement).", "이 계정은 영상을 내보내거나 들여올 권한이 없습니다(진료 · 수납 · 접수 권한 가운데 하나가 필요).", "This account may neither copy out nor bring in images (Consultation, Payment or Registration is needed)." } },
      { "e_NO_PATIENT", new[] { "Aucun patient avec ce N° dossier.", "이 차트번호의 환자가 없습니다.", "No patient with this chart number." } },
      { "e_CANCELLED", new[] { "examen annulé", "취소된 검사", "cancelled exam" } },
      { "e_NO_IMAGES", new[] { "pas d'images", "영상 없음", "no images" } },
      { "e_IDENTITY", new[] { "avertissement d'identité : à régler d'abord dans l'EMR", "환자 번호 경고 — EMR에서 먼저 바로잡으세요", "identity warning: settle it in the EMR first" } },
      { "e_BUSY",     new[] { "correction en cours : réessayez dans quelques minutes", "영상을 바로잡는 중 — 몇 분 뒤에 다시", "being corrected: try again in a few minutes" } },
      { "e_NOT_ON_SERVER", new[] { "images absentes du serveur d'images", "영상 서버에 영상이 없음", "images missing on the image server" } },
      { "e_UNREACHABLE", new[] { "Le serveur d'images ne répond pas. Réessayez dans un instant.", "영상 서버가 응답하지 않습니다. 잠시 뒤에 다시 하세요.", "The image server does not answer. Try again in a moment." } },
      { "e_NOT_PAIRED", new[] { "Le serveur d'images n'est pas relié à l'EMR. Prévenez l'administrateur.", "영상 서버가 EMR과 연결되어 있지 않습니다. 관리자에게 알리세요.", "The image server is not linked to the EMR. Tell the administrator." } },
      { "e_NOT_LOGGED", new[] { "Le journal des modifications n'a pas pu être écrit : rien n'a été copié.", "변경 기록을 남기지 못했습니다. 아무것도 반출하지 않았습니다.", "The change log could not be written: nothing was copied." } },
      { "e_OTHER_PATIENT", new[] { "Les examens ne sont pas du même patient.", "같은 환자의 검사가 아닙니다.", "The exams are not of the same patient." } },
      { "e_TOO_MANY_EXAMS", new[] { "Trop d'examens à la fois.", "한 번에 반출하기에는 검사가 너무 많습니다.", "Too many exams at a time." } },
      { "e_BROKEN",   new[] { "La connexion a été coupée pendant la récupération. Rien n'a été copié ; recommencez.", "받는 도중에 연결이 끊겼습니다. 아무것도 반출하지 않았습니다. 다시 하세요.", "The connection was cut while fetching. Nothing was copied; start again." } },
      { "e_BAD_BUNDLE", new[] { "Les images reçues sont incomplètes. Rien n'a été copié ; recommencez.", "받은 영상이 온전하지 않습니다. 아무것도 반출하지 않았습니다. 다시 하세요.", "The images received are incomplete. Nothing was copied; start again." } },
      { "e_NO_ROOM",  new[] { "Pas assez de place à cet endroit : il faut {0}, il reste {1}.", "그 자리에 공간이 모자랍니다: {0} 필요, {1} 남음.", "Not enough room there: {0} needed, {1} left." } },
      { "e_NO_FOLDER", new[] { "Ce dossier n'existe pas.", "그 폴더가 없습니다.", "This folder does not exist." } },
      { "e_WRITE_FAILED", new[] { "La copie a échoué : {0}", "복사에 실패했습니다: {0}", "The copy failed: {0}" } },
      { "e_NOT_VERIFIED", new[] { "La copie a été relue et elle est différente de l'original ({0} fichier(s)).\nSupprimez le dossier {1} et recommencez.", "사본을 다시 읽었더니 원본과 다릅니다(파일 {0}개).\n{1} 폴더를 지우고 다시 하세요.", "The copy was read back and differs from the original ({0} file(s)).\nDelete the folder {1} and start again." } },
      { "e_EXISTS",   new[] { "Ce fichier existe déjà. Choisissez un autre nom.", "같은 이름의 파일이 이미 있습니다. 다른 이름을 고르세요.", "This file already exists. Choose another name." } },
      { "e_ISO",      new[] { "Le fichier ISO n'a pas pu être écrit : {0}", "ISO 파일을 쓰지 못했습니다: {0}", "The ISO file could not be written: {0}" } },
      // ── the two ways: copy out, bring in ──
      { "modeExport", new[] { "Copier vers un CD", "CD로 내보내기", "Copy to a CD" } },
      { "modeImport", new[] { "Importer un CD / une clé USB", "CD · USB 들여오기", "Bring in a CD / USB stick" } },
      // ── bringing in another hospital's disc ──
      { "impNoSource", new[] { "Choisissez le CD ou le dossier (clé USB) à importer.", "들여올 CD나 폴더(USB)를 고르세요.", "Choose the CD or the folder (USB stick) to bring in." } },
      { "impSource", new[] { "Source : {1} examen(s), {2} image(s) — {0}", "가져올 곳: 검사 {1}건, 영상 {2}장 — {0}", "Source: {1} exam(s), {2} image(s) — {0}" } },
      { "impSkipped", new[] { " · {0} fichier(s) ignoré(s) (pas des images)", " · 영상이 아닌 파일 {0}개는 뺌", " · {0} file(s) left out (not images)" } },
      { "impNothing", new[] { "Source : aucune image DICOM dans ce dossier — {0}", "가져올 곳: 이 폴더에는 DICOM 영상이 없습니다 — {0}", "Source: no DICOM image in this folder — {0}" } },
      { "impChoose", new[] { "Choisir le disque ou le dossier…", "디스크 · 폴더 고르기…", "Choose the disc or folder…" } },
      { "askSource", new[] { "Choisissez le CD ou le dossier qui contient les images à importer", "들여올 영상이 든 CD나 폴더를 고르세요", "Choose the CD or the folder that holds the images to bring in" } },
      { "colHospital", new[] { "Établissement", "병원", "Hospital" } },
      { "colDiscPatient", new[] { "Patient (disque)", "디스크의 환자", "Patient (disc)" } },
      { "impReading", new[] { "Lecture du disque… {0} / {1}", "디스크를 읽는 중… {0} / {1}", "Reading the disc… {0} / {1}" } },
      { "impDiscPatient", new[] { "Sur le disque : {0} · N° {1} · né(e) le {2} · {3}", "디스크의 환자: {0} · 번호 {1} · 생년월일 {2} · {3}", "On the disc: {0} · no. {1} · born {2} · {3}" } },
      { "impDiscPatients", new[] { "Ce disque contient les images de {0} patients : importez un patient à la fois.", "이 디스크에는 환자 {0}명의 영상이 있습니다. 한 번에 한 환자씩 들여오세요.", "This disc holds the images of {0} patients: bring in one patient at a time." } },
      { "impSelNone", new[] { "Cochez les examens à importer.", "들여올 검사를 체크하세요.", "Tick the exams to bring in." } },
      { "impNeedPatient", new[] { "Tapez d'abord le N° dossier du patient qui recevra les images.", "먼저 영상을 받을 환자의 차트번호를 치세요.", "First type the chart number of the patient who will receive the images." } },
      { "impRoom", new[] { "Place sur le serveur d'images : {0}", "영상 서버의 남은 자리: {0}", "Room on the image server: {0}" } },
      { "impBefore", new[] { "Déjà importé pour ce patient : {0} examen(s).", "이 환자에게 이미 들여온 검사: {0}건.", "Already brought in for this patient: {0} exam(s)." } },
      { "impRoomNo", new[] { "  ✘ pas assez de place pour cette sélection", "  ✘ 이 선택에는 자리가 모자랍니다", "  ✘ not enough room for this selection" } },
      { "impButton", new[] { "Importer…", "들여오기…", "Bring in…" } },
      { "impCancel", new[] { "Annuler", "취소", "Cancel" } },
      { "s_OURS", new[] { "examen réalisé ici : déjà dans le dossier", "우리 병원에서 찍은 검사 — 이미 차트에 있음", "done here: already in the chart" } },
      { "s_HERE", new[] { "déjà importé le {0}", "{0}에 이미 들여옴", "already brought in on {0}" } },
      { "s_OTHER", new[] { "déjà dans le dossier d'un autre patient — vérifiez que ce disque est bien celui de ce patient", "다른 환자의 차트에 이미 있음 — 이 환자의 디스크가 맞는지 확인하세요", "already in another patient's chart — check that this disc is this patient's" } },
      { "s_BUSY", new[] { "importation en cours — réessayez dans un instant", "지금 들여오는 중 — 잠시 뒤에 다시", "being brought in — try again in a moment" } },
      { "s_ON_SERVER", new[] { "déjà sur le serveur d'images — prévenez l'administrateur", "영상 서버에 이미 있음 — 관리자에게 알리세요", "already on the image server — tell the administrator" } },
      { "s_UNREACHABLE", new[] { "le serveur d'images ne répond pas", "영상 서버가 응답하지 않음", "the image server does not answer" } },
      { "s_TOO_BIG", new[] { "un fichier dépasse {0} : ne peut pas être importé", "파일 하나가 {0}를 넘어 들여올 수 없음", "a file is larger than {0}: cannot be brought in" } },
      { "impOnePatient", new[] { "Les examens cochés ne sont pas du même patient sur le disque. Importez un patient à la fois.", "체크한 검사가 디스크에서 같은 환자의 것이 아닙니다. 한 번에 한 환자씩 들여오세요.", "The ticked exams are not of the same patient on the disc. Bring in one patient at a time." } },
      { "impWarnBig", new[] { "L'examen « {0} » est volumineux ({1}) : l'importation peut être longue. Continuer ?", "「{0}」 검사는 큽니다({1}). 들여오는 데 오래 걸릴 수 있습니다. 계속할까요?", "The exam \"{0}\" is large ({1}): bringing it in may take long. Go on?" } },
      { "impVerify", new[] { "Vérification des fichiers… {0} / {1}", "파일을 확인하는 중… {0} / {1}", "Checking the files… {0} / {1}" } },
      { "impSending", new[] { "Envoi… examen {0} / {1} — image {2} / {3}", "보내는 중… 검사 {0} / {1} — 영상 {2} / {3}", "Sending… exam {0} / {1} — image {2} / {3}" } },
      { "impRetry", new[] { "Nouvel essai… examen {0} / {1} — image {2} / {3}", "다시 보내는 중… 검사 {0} / {1} — 영상 {2} / {3}", "Trying again… exam {0} / {1} — image {2} / {3}" } },
      { "impFinishing", new[] { "Enregistrement dans le dossier…", "차트에 넣는 중…", "Putting it in the chart…" } },
      { "impCancelling", new[] { "Annulation…", "취소하는 중…", "Cancelling…" } },
      { "impDone", new[] { "Terminé : {0} examen(s), {1} image(s) importé(s) dans le dossier de {2}.\n\nIls sont visibles dans l'EMR : Imagerie → Imagerie externe (CD / USB).", "끝났습니다. 검사 {0}건, 영상 {1}장을 {2} 님의 차트에 들여왔습니다.\n\nEMR의 영상/판독 → 외부 영상 (CD / USB)에서 보입니다.", "Done: {0} exam(s), {1} image(s) brought into the chart of {2}.\n\nThey are in the EMR: Imaging → Outside images (CD / USB)." } },
      { "impNotAll", new[] { "\n\n{0} examen(s) n'ont pas été importés.", "\n\n검사 {0}건은 들여오지 못했습니다.", "\n\n{0} exam(s) were not brought in." } },
      { "impUndrawn", new[] { "\n\n(Le serveur d'images ne sait pas afficher certaines séries : {0}. Elles sont enregistrées, mais peuvent ne pas s'afficher.)", "\n\n(영상 서버가 그리지 못하는 시리즈가 있습니다: {0}. 저장은 됐지만 화면에 안 보일 수 있습니다.)", "\n\n(The image server cannot draw some series: {0}. They are stored, but may not show.)" } },
      { "impDropped", new[] { "\n\n({0} fichier(s) du disque n'étaient pas des images de ces examens : non envoyés.)", "\n\n(디스크의 파일 {0}개는 이 검사의 영상이 아니어서 보내지 않았습니다.)", "\n\n({0} file(s) of the disc were not images of these exams: not sent.)" } },
      { "impCancelled", new[] { "Importation annulée. Rien n'a été ajouté au dossier pour l'examen en cours.", "들여오기를 취소했습니다. 하던 검사는 차트에 아무것도 들어가지 않았습니다.", "Bringing in was cancelled. Nothing of the exam in progress was added to the chart." } },
      { "impFailed", new[] { "L'examen « {0} » n'a pas été importé :\n{1}", "「{0}」 검사를 들여오지 못했습니다:\n{1}", "The exam \"{0}\" was not brought in:\n{1}" } },
      { "impContinue", new[] { "\n\nContinuer avec les examens suivants ?", "\n\n다음 검사를 계속할까요?", "\n\nGo on with the next exams?" } },
      { "impEmpty", new[] { "aucun fichier image lisible pour cet examen", "이 검사에는 읽을 수 있는 영상 파일이 없음", "no readable image file for this exam" } },
      // ── the "is this the same patient?" window ──
      { "cfTitle", new[] { "Confirmer le patient", "환자 확인", "Confirm the patient" } },
      { "cfDisc", new[] { "Sur le disque", "디스크", "On the disc" } },
      { "cfChart", new[] { "Dans le dossier (EMR)", "우리 차트 (EMR)", "In the chart (EMR)" } },
      { "cfName", new[] { "Nom", "이름", "Name" } },
      { "cfNumber", new[] { "N°", "번호", "No." } },
      { "cfBirth", new[] { "Né(e) le", "생년월일", "Born" } },
      { "cfSex", new[] { "Sexe", "성별", "Sex" } },
      { "cfSame", new[] { "✔", "✔", "✔" } },
      { "cfDiffer", new[] { "✘ différent", "✘ 다름", "✘ different" } },
      { "cfNameNote", new[] { "Le nom n'est pas comparé : chaque hôpital l'écrit à sa façon.", "이름은 병원마다 적는 법이 달라 비교하지 않습니다.", "The name is not compared: every hospital writes it its own way." } },
      { "cfExams", new[] { "À importer :", "들여올 것:", "To bring in:" } },
      { "cfImages", new[] { "{0} image(s)", "영상 {0}장", "{0} image(s)" } },
      { "cfMore", new[] { "… et {0} autre(s)", "… 그 밖에 {0}건", "… and {0} more" } },
      { "cfCheck", new[] { "Je confirme que ces images sont celles de ce patient.", "이 영상이 이 환자의 것이 맞습니다.", "I confirm that these images are this patient's." } },
      { "cfCheckDiffer", new[] { "La date de naissance ou le sexe sont différents. Je confirme malgré tout que ces images sont celles de ce patient.", "생년월일 또는 성별이 다릅니다. 그래도 이 환자의 영상이 맞습니다.", "The date of birth or the sex differ. I confirm all the same that these images are this patient's." } },
      { "cfGo", new[] { "Importer", "들여오기", "Bring in" } },
      // ── refusals while bringing in ──
      { "e_NO_IMPORT", new[] { "Cet EMR ne sait pas encore importer des images (version trop ancienne).", "이 EMR은 아직 영상 들여오기를 하지 못합니다(판이 오래됨).", "This EMR cannot bring in images yet (its version is too old)." } },
      { "e_NO_ROOM_SERVER", new[] { "Pas assez de place sur le serveur d'images : il faut {0}, il reste {1}.", "영상 서버에 자리가 모자랍니다: {0} 필요, {1} 남음.", "Not enough room on the image server: {0} needed, {1} left." } },
      { "e_TOO_BIG_FILE", new[] { "Un fichier dépasse la taille autorisée ({0}).", "파일 하나가 허용 크기({0})를 넘습니다.", "A file is larger than what is allowed ({0})." } },
      { "e_NOT_DICOM", new[] { "Le serveur d'images a refusé un fichier : ce n'est pas une image DICOM lisible.", "영상 서버가 파일 하나를 받지 않았습니다. 읽을 수 있는 DICOM 영상이 아닙니다.", "The image server refused a file: it is not a readable DICOM image." } },
      { "e_NOT_OF_STUDY", new[] { "Un fichier n'appartient pas à cet examen ou à ce patient du disque.", "파일 하나가 이 검사 또는 디스크의 이 환자의 것이 아닙니다.", "A file does not belong to this exam or to this patient of the disc." } },
      { "e_CHANGE_FAILED", new[] { "Le serveur d'images n'a pas pu enregistrer une image sous le N° de ce patient.", "영상 서버가 영상을 이 환자의 번호로 저장하지 못했습니다.", "The image server could not store an image under this patient's number." } },
      { "e_INCOMPLETE", new[] { "Toutes les images ne sont pas arrivées ({0} sur {1}).", "영상이 다 도착하지 않았습니다({1}장 가운데 {0}장).", "Not every image arrived ({0} of {1})." } },
      { "e_CLOSED", new[] { "Cette importation est déjà terminée ou annulée.", "이 들여오기는 이미 끝났거나 취소되었습니다.", "This import is already finished or cancelled." } },
      { "e_NOT_YOURS", new[] { "Cette importation a été commencée par un autre compte.", "이 들여오기는 다른 계정이 시작한 것입니다.", "This import was started by another account." } },
      { "e_NOT_FOUND", new[] { "Importation introuvable sur le serveur.", "서버에 이 들여오기가 없습니다.", "The import was not found on the server." } },
      { "e_UNREADABLE", new[] { "Un fichier du disque n'a pas pu être lu (disque rayé ou retiré ?).", "디스크의 파일을 읽지 못했습니다(디스크가 긁혔거나 빠졌나요?).", "A file of the disc could not be read (scratched disc, or taken out?)." } },
      { "e_BAD_REQUEST", new[] { "L'EMR n'a pas accepté la demande : {0}", "EMR이 요청을 받지 않았습니다: {0}", "The EMR did not accept the request: {0}" } },
      { "e_NOT_LOGGED_IMPORT", new[] { "Le journal des modifications n'a pas pu être écrit : rien n'a été ajouté au dossier.", "변경 기록을 남기지 못했습니다. 차트에 아무것도 들어가지 않았습니다.", "The change log could not be written: nothing was added to the chart." } },
      { "e_BROKEN_IMPORT", new[] { "La connexion avec l'EMR a été coupée pendant l'envoi.", "보내는 도중에 EMR과의 연결이 끊겼습니다.", "The connection to the EMR was cut while sending." } },
      { "e_other",    new[] { "Erreur : {0}", "오류: {0}", "Error: {0}" } },
    };
  }
}
